name: update lists

on:
  schedule:
    - cron:  '5 4 * * *'
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/go.yml'
      - 'go.*'
      - '*.go'

jobs:
  build:
    name: Update
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build and update
      run: |
        env CGO_ENABLED=0 go build -o update .
        ./update
	line=`cat toblock.lst | wc -l` && echo "toblock.lst contains $line lines"
	line=`cat toblock-optimized.lst | wc -l` && echo "toblock-optimized.lst contains $line lines"
	line=`cat toblock-without-shorturl.lst | wc -l` && echo "toblock-without-shorturl.lst contains $line lines"
	line=`cat toblock-without-shorturl-optimized.lst | wc -l` && echo "toblock-without-shorturl-optimized.lst contains $line lines"

    - name: Set up Git
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}        
      run: |
        git config user.name "auto-update-lists[bot]"
        git config user.email "auto-update-lists[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

    - name: Commit and push changes
      run: |
        git pull origin master
        git commit -m "auto update lists at $(date)" *.lst
        git push -f origin master

